### ISSUE TITLE
Update for new version of Curry8

### ISSUE THREAD

**Issue by andyleynes** [mattpontifex/loadcurry#1]
Hello,
First let me thank you for writing the loadcurry script. Being able to seamlessly synch EEGLAB with Curry8 files is fantastic.

I am writing to let you know that the newest version of Curry8 changed the output filenames (I confirmed this with Neuroscan today). It used to output the data in "*.cdt" files and the channel info in "*.cdt.dpa". The version changed the name of the second file to "*.cdt.dpo". The a is changed to an "o". Neuroscan assures it is just a name change.

When you try to import the new datafiles you get an error because there is no "*cdt.dpa" file. I think this is a trivial fix because you just have to insert a command to look for *.cdt.dpa" [old files] OR "*.cdt.dpo" [new files]. Thanks in advance!

**Comment by mattpontifex** [comment]
Thanks for letting me know! The Curry team just sent an update for Curry9 indicating this change as well. I've updated the code so it should work properly with the new file name. Please let me know if you get an error.
