### ISSUE TITLE
loadcurry3.0

### ISSUE THREAD

**Issue by andyleynes** [mattpontifex/loadcurry#2]
Hello,
Thanks so much for updating the loadcurry plug in for EEGLAB. I tried it but I still get an error with the "*.cdt.dpo" file. Maybe, I didn't install it correctly? I put it in the EEGLAB plugins folder and saw "loadcurry3.0" in the messages when EEGLAB loads, but I still get an error when I try to import a datafile with "*cdt" and "*cdt.dpo" filenames.

**Comment by mattpontifex** [comment]
Sounds like you installed it correctly. I just had the exist call flipped. Now it should work.
