### ISSUE TITLE
loadcurry v3.0

### ISSUE THREAD

**Issue by andyleynes** [mattpontifex/loadcurry#3]
Sorry to keep raising this issue, but loadcurry v3.0 is not working for me. I tried loading the new file version ("*cdt.dpo") and the old version ("*cdt.dpa") and neither worked. I am attaching a screen shot.
![loadcurryv3_0](https://user-images.githubusercontent.com/66789479/108530937-1e17a080-72a4-11eb-8639-545fd822c1ba.png)

I am running EEGLAB 2019.1

**Comment by mattpontifex** [comment]
Not a problem. Sorry it keeps erroring on you. Can you share (google drive link) an example file that you are having the issue with? That way I can see specifically why its having the issue. Clearly its happening on the read in at line 135, but the new version works on test files on my end. Do the .cdt.dpo and the .cdt.dpa files happen to have the same name (i.e., you have testfile.cdt.dpo in the same folder as testfile.cdt.dpa)?

**Comment by andyleynes** [comment]
Thanks. I sent a link with data access.
