### ISSUE TITLE
Unit in EEG.times should be in milliseconds

### ISSUE THREAD

**Issue by CloudyDory** [mattpontifex/loadcurry#4]
Hi, on lines 531-533 of loadcurry.m, the `xmin`, `xmax`, and `times` fields of EEG is set by:
```
EEG.xmin = 0;
EEG.xmax = (EEG.pnts-1)/EEG.srate+EEG.xmin;
EEG.times = linspace(EEG.xmin,EEG.xmax,EEG.pnts);
```
In `eeg_checkset.m`, the units of these fields are specified:
```
%   EEG.xmin         - epoch start latency|time (in sec. relative to the time-locking event at time 0)
%   EEG.xmax         - epoch end latency|time (in seconds)
%   EEG.times        - vector of latencies|times in miliseconds (one per time point)
```

So I guess unit of `EEG.times` in the current version (3.2.2) of `loadcurry.m` is incorrectly set as seconds. The unit was correct in version 2.0. 

Best,
Zhou

**Comment by mattpontifex** [comment]
Great catch. It is fixed in 3.2.3
