### ISSUE TITLE
v3.3.0 fails to load .dat files on unix operating systems

### ISSUE THREAD

**Issue by simonmarchant** [mattpontifex/loadcurry#6]
Hi, thanks for maintaining this plugin, it's really helpful. I found an issue with the latest version (3.3.0) where loadcurry errors out. You can reproduce this by selecting "from Neuroscan Curry files" from the EEGlab menu, and selecting a .dat file. The program fails with the error message `Unrecognized function or variable 'parameterFile2'.`. I have tracked it down to the line here, which adds a backslash to create a filepath. This works on Windows operating systems but fails on unix-based operating systems, which needs a forward slash. 

https://github.com/mattpontifex/loadcurry/blob/a85dc2d37ccdad5805f544322dca669800066b77/loadcurry3.3.0/LoadCurryDataFile.m#L88

I have made a fix, which is testing fine on .dat files (I don't think the problem impacts .cdt files, but I have no .cdt files to test on, so I haven't confirmed this). I can make a pull request for this for approval. I hope that this is OK.

**Comment by mattpontifex** [comment]
Great catch
